language: android
script: "./gradlew assembleDebug"

jdk:
  - oraclejdk8

android:
  components:
    # The BuildTools version used by your project
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-27
    - android-28
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-27
    - addon-google_apis-google-28
  licenses:
    - android-sdk-license-.+
